### ISSUE TITLE
Pre-compiled

### ISSUE THREAD

**Issue by tuliogit** [wolkenschieber/spy-camera-os#1]
I was wondering if the original author of this app still develops it. And then I found out this fork, with recent developments. I wonder what changed. I wonder how to find a pre-compiled version of it, an ad-free one, and with the hidden features activated (like record videos with Vol-Up pressed)

**Comment by wolkenschieber** [comment]
Nothing of the functionality has been changed. The project has only converted into an Android Studio project. So if there are hidden features in the original, then these are also here.

I won't provide any builds nor remove the ads from the code. The original author wants this code to be used "in an ethical way and to respect his effort".
