### ISSUE TITLE
Is this a Virus?

### ISSUE THREAD

**Issue by Ogi22po** [wolkenschieber/spy-camera-os#3]
Why is this aplication now not on Google Play?
Why is the app on my mobile so strange?
I suspect this is fraudulent software that tries to look like opensource.

The developer offers the app on this page spycameraos*com
Please, community, can you check it out?

**Comment by wolkenschieber** [comment]
This repository forked the project in Dec 2014 and hasn't been updated since. Seems that the original author has removed it from Google Play.
